### ISSUE TITLE
Option to sort threads by name

### ISSUE THREAD

**Issue by alyti** [emilk/puffin_egui#1]
There's an attempt at using puffin_egui in bevy, and currently the compute threads are a bit out-of-order.
I suspect one solution would be to provide an option to sort the streams here: 
https://github.com/emilk/puffin_egui/blob/ba608f9d2fa20c89317fd3990491a103c0c88771/src/lib.rs#L327
![Screenshot](https://cdn.discordapp.com/attachments/692572690833473578/840154138481262612/unknown.png)

**Comment by emilk** [comment]
Sounds like a good idea! If I recall correctly, the default sorting of puffin is chronological (bottom-up), i.e. in what order the threads first report data. The motivation for that it will likely follow casual order (i.e. child threads will end up above their parents, and jobs on worker threads will end up above the threads that spawned them). So lexicographical sorting is a good idea, but should (as you say) be an *option*, i.e. behind a checkbox.

**Comment by emilk** [comment]
We should probably sort them using something like https://crates.io/crates/natord

**Comment by emilk** [comment]
I moved this issue to https://github.com/EmbarkStudios/puffin/issues/28 (since I've moved all of puffin_egui there)
